var hiraganaCards =[
    {source:'あ', target: 'a', success:0, error: 0},
    {source:'か', target: 'ka', success:0, error: 0},
    {source:'さ', target: 'sa', success:0, error: 0},
    {source:'た', target: 'ta', success:0, error: 0},
    {source:'な', target: 'na', success:0, error: 0},
    {source:'は', target: 'ha', success:0, error: 0},
    {source:'ま', target: 'ma', success:0, error: 0},
    {source:'や', target: 'ya', success:0, error: 0},
    {source:'ら', target: 'ra', success:0, error: 0},
    {source:'わ', target: 'wa', success:0, error: 0},
    {source:'ん', target: 'n', success:0, error: 0},

    {source:'い', target: 'i', success:0, error: 0},
    {source:'き', target: 'ki', success:0, error: 0},
    {source:'し', target: 'shi', success:0, error: 0},
    {source:'ち', target: 'chi', success:0, error: 0},
    {source:'に', target: 'ni', success:0, error: 0},
    {source:'ひ', target: 'hi', success:0, error: 0},
    {source:'み', target: 'mi', success:0, error: 0},
    {source:'り', target: 'ri', success:0, error: 0},

    {source:'う', target: 'u', success:0, error: 0},
    {source:'く', target: 'ku', success:0, error: 0},
    {source:'す', target: 'su', success:0, error: 0},
    {source:'つ', target: 'tsu', success:0, error: 0},
    {source:'ぬ', target: 'nu', success:0, error: 0},
    {source:'ふ', target: 'fu', success:0, error: 0},
    {source:'む', target: 'mu', success:0, error: 0},
    {source:'ゆ', target: 'yu', success:0, error: 0},
    {source:'る', target: 'ru', success:0, error: 0},

    {source:'え', target: 'e', success:0, error: 0},
    {source:'け', target: 'ke', success:0, error: 0},
    {source:'せ', target: 'se', success:0, error: 0},
    {source:'て', target: 'te', success:0, error: 0},
    {source:'ね', target: 'ne', success:0, error: 0},
    {source:'へ', target: 'he', success:0, error: 0},
    {source:'め', target: 'me', success:0, error: 0},
    {source:'れ', target: 're', success:0, error: 0},

    {source:'お', target: 'o', success:0, error: 0},
    {source:'こ', target: 'ko', success:0, error: 0},
    {source:'そ', target: 'so', success:0, error: 0},
    {source:'と', target: 'to', success:0, error: 0},
    {source:'の', target: 'no', success:0, error: 0},
    {source:'ほ', target: 'ho', success:0, error: 0},
    {source:'も', target: 'mo', success:0, error: 0},
    {source:'よ', target: 're', success:0, error: 0},
    {source:'も', target: 'mo', success:0, error: 0},
    {source:'ろ', target: 'ro', success:0, error: 0},
    {source:'を', target: 'wo', success:0, error: 0},
];