const deck = {
    name: 'Capitals of the world',
    description: 'Learn the main capitals of the world with this wonderful deck',
    cards: [
         {q: 'Afghanistan', a: 'Kabul'},
         {q: 'Algeria', a: 'Algiers'},
         {q: 'Angola', a: 'Luanda'},
         {q: 'Argentina', a: 'Buenos Aires'},
         {q: 'Australia', a: 'Canberra'},
         {q: 'Austria', a: 'Vienna'},
         {q: 'Belgium', a: 'Brussels'},
         {q: 'Bolivia', a: 'La Paz'},
         {q: 'Bosnia and Herzegovina', a: 'Sarajevo'},
         {q: 'Brazil', a: 'Brasilia'},
         {q: 'Bulgaria', a: 'Sofia'},
         {q: 'Burkina Faso', a:  'Ouagadougou'},
         {q: 'Cambodia', a: 'Phnom Penh'},
         {q: 'Cameroon', a: 'Yaounde'},
         {q: 'Canada', a: 'Ottawa'},
         {q: 'Cape Verde', a: 'Praia'},
         {q: 'Chile', a: 'Santiago'},
         {q: 'China', a: 'Beijing'},
         {q: 'Colombia', a: 'Bogota'},
         {q: 'Cote d\'Ivoire', a: 'Yamoussoukro'},
         {q: 'Croatia', a: 'Zagreb'},
         {q: 'Cuba', a: 'Havana'},
         {q: 'Czech Republic', a: 'Prague'},
         {q: 'Denmark', a: 'Copenhagen'},
         {q: 'Egypt', a: 'Cairo'},
         {q: 'Ethiopia', a: 'Addis Ababa'},
         {q: 'Finland', a: 'Helsinki'},
         {q: 'France', a: 'Paris'},
         {q: 'Germany', a: 'Berlin'},
         {q: 'Greece', a: 'Athens'},
         {q: 'Haiti', a: 'Port-au-Prince'},
         {q: 'Hungary', a: 'Budapest'},
         {q: 'Iceland', a: 'Reykjavik'},
         {q: 'India', a: 'New Delhi'},
         {q: 'Indonesia', a: 'Jakarta'},
         {q: 'Iran', a: 'Tehran'},
         {q: 'Iraq', a: 'Baghdad'},
         {q: 'Ireland', a: 'Dublin'},
         {q: 'Israel', a: 'Jerusalem'},
         {q: 'Italy', a: 'Rome'},
         {q: 'Jamaica', a: 'Kingston'},
         {q: 'Japan', a: 'Tokyo'},
         {q: 'Kenya', a: 'Nairobi'},
         {q: 'Korea, North', a: 'Pyongyang'},
         {q: 'Korea, South', a: 'Seoul'},
         {q: 'Kuwait', a: 'Kuwait City'},
         {q: 'Lebanon', a: 'Beirut'},
         {q: 'Libya', a: 'Tripoli'},
         {q: 'Lithuania', a: 'Vilnius'},
         {q: 'Luxembourg ', a: 'Luxembourg'},
         {q: 'Madagascar ', a: 'Antananarivo'},
         {q: 'Malaysia', a: 'Kuala Lumpur'},
         {q: 'Mali', a: 'Bamako'},
         {q: 'Mexico', a: 'Mexico City'},
         {q: 'Monaco', a: 'Monaco'},
         {q: 'Mongolia', a: 'Ulaanbaatar'},
         {q: 'Morocco', a: 'Rabat'},
         {q: 'Nepal', a: 'Kathmandu'},
         {q: 'Netherlands ', a: 'Amsterdam'},
         {q: 'New Zealand', a: 'Wellington'},
         {q: 'Norway', a: 'Oslo'},
         {q: 'Pakistan', a: 'Islamabad'},
         {q: 'Paraguay', a: 'Asuncion'},
         {q: 'Peru', a: 'Lima'},
         {q: 'Philippines ', a: 'Manila'},
         {q: 'Poland', a: 'Warsaw'},
         {q: 'Portugal', a: 'Lisbon'},
         {q: 'Romania', a: 'Bucharest'},
         {q: 'Russia', a: 'Moscow'},
         {q: 'Rwanda', a: 'Kigali'},
         {q: 'Saudi Arabia', a: 'Riyadh'},
         {q: 'Senegal', a: 'Dakar'},
         {q: 'Serbia', a: 'Belgrade'},
         {q: 'Sierra Leone', a: 'Freetown'},
         {q: 'Singapore', a: 'Singapore'},
         {q: 'Somalia', a: 'Mogadishu'},
         {q: 'South Africa', a: 'Pretoria'},
         {q: 'Spain', a: 'Madrid'},
         {q: 'Sweden', a: 'Stockholm'},
         {q: 'Switzerland ', a: 'Bern'},
         {q: 'Syria', a: 'Damascus'},
         {q: 'Taiwan', a: 'Taipei'},
         {q: 'Thailand', a: 'Bangkok'},
         {q: 'Togo', a: 'Lome'},
         {q: 'Tunisia', a: 'Tunis'},
         {q: 'Turkey', a: 'Ankara'},
         {q: 'United Arab Emirates', a: 'Abu Dhabi'},
         {q: 'United Kingdom', a: 'London'},
         {q: 'United States of America', a: 'Washington D.C.'},
         {q: 'Uruguay', a: 'Montevideo'},
         {q: 'Venezuela', a: 'Caracas'},
         {q: 'Vietnam', a: 'Hanoi'}
    ]
};

export default deck;
