var capitals =
{
    name: 'Capitals of the world',
    description: 'Learn the main capitals of the world with this wonderful deck',
    cards: [
         {source: 'Afghanistan', target: 'Kabul'},
         {source: 'Albania', target: 'Tirana'},
         {source: 'Algeria', target: 'Algiers'},
         {source: 'Andorra', target: 'Andorra la Vella'},
         {source: 'Angola', target: 'Luanda'},
         {source: 'Antigua and Barbuda', target: 'Saint John\'s'},
         {source: 'Argentina', target: 'Buenos Aires'},
         {source: 'Armenia', target: 'Yerevan'},
         {source: 'Australia', target: 'Canberra'},
         {source: 'Austria', target: 'Vienna'},
         {source: 'Azerbaijan ', target: 'Baku'},
         {source: 'The Bahamas', target: 'Nassau'},
         {source: 'Bahrain', target: 'Manama'},
         {source: 'Bangladesh ', target: 'Dhaka'},
         {source: 'Barbados', target: 'Bridgetown'},
         {source: 'Belarus', target: 'Minsk'},
         {source: 'Belgium', target: 'Brussels'},
         {source: 'Belize', target: 'Belmopan'},
         {source: 'Benin', target: 'Porto-Novo'},
         {source: 'Bhutan', target: 'Thimphu'},
         {source: 'Bolivia', target: 'La Paz'},
         {source: 'Bosnia and Herzegovina', target: 'Sarajevo'},
         {source: 'Botswana', target: 'Gaborone'},
         {source: 'Brazil', target: 'Brasilia'},
         {source: 'Brunei', target: 'Bandar Seri Begawan'},
         {source: 'Bulgaria', target: 'Sofia'},
         {source: 'Burkina Faso', target:  'Ouagadougou'},
         {source: 'Burundi', target: 'Bujumbura'},
         {source: 'Cambodia', target: 'Phnom Penh'},
         {source: 'Cameroon', target: 'Yaounde'},
         {source: 'Canada', target: 'Ottawa'},
         {source: 'Cape Verde', target: 'Praia'},
         {source: 'Central African Republic', target: 'Bangui'},
         {source: 'Chad', target: 'N\'Djamena'},
         {source: 'Chile', target: 'Santiago'},
         {source: 'China', target: 'Beijing'},
         {source: 'Colombia', target: 'Bogota'},
         {source: 'Comoros', target: 'Moroni'},
         {source: 'Congo, Republic of the', target: 'Brazzaville'},
         {source: 'Congo, Democratic Republic of the', target: 'Kinshasa'},
         {source: 'Costa Rica ', target: 'San Jose'},
         {source: 'Cote d\'Ivoire', target: 'Yamoussoukro'},
         {source: 'Croatia', target: 'Zagreb'},
         {source: 'Cuba', target: 'Havana'},
         {source: 'Cyprus', target: 'Nicosia'},
         {source: 'Czech Republic', target: 'Prague'},
         {source: 'Denmark', target: 'Copenhagen'},
         {source: 'Djibouti', target: 'Djibouti'},
         {source: 'Dominica', target: 'Roseau'},
         {source: 'Dominican Republic', target: 'Santo Domingo'},
         {source: 'East Timor (Timor-Leste)', target: 'Dili'},
         {source: 'Ecuador', target: 'Quito'},
         {source: 'Egypt', target: 'Cairo'},
         {source: 'El Salvador', target: 'San Salvador'},
         {source: 'Equatorial Guinea', target: 'Malabo'},
         {source: 'Eritrea', target: 'Asmara'},
         {source: 'Estonia', target: 'Tallinn'},
         {source: 'Ethiopia', target: 'Addis Ababa'},
         {source: 'Fiji', target: 'Suva'},
         {source: 'Finland', target: 'Helsinki'},
         {source: 'France', target: 'Paris'},
         {source: 'Gabon', target: 'Libreville'},
         {source: 'The Gambia', target: 'Banjul'},
         {source: 'Georgia', target: 'Tbilisi'},
         {source: 'Germany', target: 'Berlin'},
         {source: 'Ghana', target: 'Accra'},
         {source: 'Greece', target: 'Athens'},
         {source: 'Grenada', target: 'Saint George\'s'},
         {source: 'Guatemala', target: 'Guatemala City'},
         {source: 'Guinea', target: 'Conakry'},
         {source: 'Guinea-Bissau', target: 'Bissau'},
         {source: 'Guyana', target: 'Georgetown'},
         {source: 'Haiti', target: 'Port-au-Prince'},
         {source: 'Honduras', target: 'Tegucigalpa'},
         {source: 'Hungary', target: 'Budapest'},
         {source: 'Iceland', target: 'Reykjavik'},
         {source: 'India', target: 'New Delhi'},
         {source: 'Indonesia', target: 'Jakarta'},
         {source: 'Iran', target: 'Tehran'},
         {source: 'Iraq', target: 'Baghdad'},
         {source: 'Ireland', target: 'Dublin'},
         {source: 'Israel', target: 'Jerusalem*'},
         {source: 'Italy', target: 'Rome'},
         {source: 'Jamaica', target: 'Kingston'},
         {source: 'Japan', target: 'Tokyo'},
         {source: 'Jordan', target: 'Amman'},
         {source: 'Kazakhstan ', target: 'Astana'},
         {source: 'Kenya', target: 'Nairobi'},
         {source: 'Kiribati', target: 'Tarawa Atoll'},
         {source: 'Korea, North', target: 'Pyongyang'},
         {source: 'Korea, South', target: 'Seoul'},
         {source: 'Kosovo', target: 'Pristina'},
         {source: 'Kuwait', target: 'Kuwait City'},
         {source: 'Kyrgyzstan ', target: 'Bishkek'},
         {source: 'Laos', target: 'Vientiane'},
         {source: 'Latvia', target: 'Riga'},
         {source: 'Lebanon', target: 'Beirut'},
         {source: 'Lesotho', target: 'Maseru'},
         {source: 'Liberia', target: 'Monrovia'},
         {source: 'Libya', target: 'Tripoli'},
         {source: 'Liechtenstein', target: 'Vaduz'},
         {source: 'Lithuania', target: 'Vilnius'},
         {source: 'Luxembourg ', target: 'Luxembourg'},
         {source: 'Macedonia', target: 'Skopje'},
         {source: 'Madagascar ', target: 'Antananarivo'},
         {source: 'Malawi', target: 'Lilongwe'},
         {source: 'Malaysia', target: 'Kuala Lumpur'},
         {source: 'Maldives', target: 'Male'},
         {source: 'Mali', target: 'Bamako'},
         {source: 'Malta', target: 'Valletta'},
         {source: 'Marshall Islands', target: 'Majuro'},
         {source: 'Mauritania ', target: 'Nouakchott'},
         {source: 'Mauritius', target: 'Port Louis'},
         {source: 'Mexico', target: 'Mexico City'},
         {source: 'Micronesia, Federated States of', target: 'Palikir'},
         {source: 'Moldova', target: 'Chisinau'},
         {source: 'Monaco', target: 'Monaco'},
         {source: 'Mongolia', target: 'Ulaanbaatar'},
         {source: 'Montenegro ', target: 'Podgorica'},
         {source: 'Morocco', target: 'Rabat'},
         {source: 'Mozambique ', target: 'Maputo'},
         {source: 'Myanmar (Burma)', target: 'Rangoon'},
         {source: 'Namibia ', target: 'Windhoek'},
         {source: 'Nepal', target: 'Kathmandu'},
         {source: 'Netherlands ', target: 'Amsterdam'},
         {source: 'New Zealand', target: 'Wellington'},
         {source: 'Nicaragua', target: 'Managua'},
         {source: 'Niger', target: 'Niamey'},
         {source: 'Nigeria', target: 'Abuja'},
         {source: 'Norway', target: 'Oslo'},
         {source: 'Oman', target: 'Muscat'},
         {source: 'Pakistan', target: 'Islamabad'},
         {source: 'Palau', target: 'Melekeok'},
         {source: 'Panama', target: 'Panama City'},
         {source: 'Papua New Guinea', target: 'Port Moresby'},
         {source: 'Paraguay', target: 'Asuncion'},
         {source: 'Peru', target: 'Lima'},
         {source: 'Philippines ', target: 'Manila'},
         {source: 'Poland', target: 'Warsaw'},
         {source: 'Portugal', target: 'Lisbon'},
         {source: 'Qatar', target: 'Doha'},
         {source: 'Romania', target: 'Bucharest'},
         {source: 'Russia', target: 'Moscow'},
         {source: 'Rwanda', target: 'Kigali'},
         {source: 'Saint Kitts and Nevis', target: 'Basseterre'},
         {source: 'Saint Lucia', target: 'Castries'},
         {source: 'Saint Vincent and the Grenadines', target: 'Kingstown'},
         {source: 'Samoa', target: 'Apia'},
         {source: 'San Marino', target: 'San Marino'},
         {source: 'Sao Tome and Principe', target: 'Sao Tome'},
         {source: 'Saudi Arabia', target: 'Riyadh'},
         {source: 'Senegal', target: 'Dakar'},
         {source: 'Serbia', target: 'Belgrade'},
         {source: 'Seychelles ', target: 'Victoria'},
         {source: 'Sierra Leone', target: 'Freetown'},
         {source: 'Singapore', target: 'Singapore'},
         {source: 'Slovakia', target: 'Bratislava'},
         {source: 'Slovenia', target: 'Ljubljana'},
         {source: 'Solomon Islands', target: 'Honiara'},
         {source: 'Somalia', target: 'Mogadishu'},
         {source: 'South Africa', target: 'Pretoria (administrative); Cape Town (legislative);  Bloemfontein (judiciary)'},
         {source: 'South Sudan', target: 'Juba (Relocating to Ramciel)'},
         {source: 'Spain', target: 'Madrid'},
         {source: 'Sri Lanka', target: 'Colombo; Sri Jayewardenepura Kotte (legislative)'},
         {source: 'Sudan', target: 'Khartoum'},
         {source: 'Suriname', target: 'Paramaribo'},
         {source: 'Swaziland', target: 'Mbabane'},
         {source: 'Sweden', target: 'Stockholm'},
         {source: 'Switzerland ', target: 'Bern'},
         {source: 'Syria', target: 'Damascus'},
         {source: 'Taiwan', target: 'Taipei'},
         {source: 'Tajikistan ', target: 'Dushanbe'},
         {source: 'Tanzania', target: 'Dar es Salaam; Dodoma (legislative)'},
         {source: 'Thailand', target: 'Bangkok'},
         {source: 'Togo', target: 'Lome'},
         {source: 'Tonga', target: 'Nuku\'alofa'},
         {source: 'Trinidad and Tobago', target: 'Port-of-Spain'},
         {source: 'Tunisia', target: 'Tunis'},
         {source: 'Turkey', target: 'Ankara'},
         {source: 'Turkmenistan', target: 'Ashgabat'},
         {source: 'Tuvalu', target: 'Vaiaku village, Funafuti province'},
         {source: 'Uganda', target: 'Kampala'},
         {source: 'Ukraine', target: 'Kyiv'},
         {source: 'United Arab Emirates', target: 'Abu Dhabi'},
         {source: 'United Kingdom', target: 'London'},
         {source: 'United States of America', target: 'Washington D.C.'},
         {source: 'Uruguay', target: 'Montevideo'},
         {source: 'Uzbekistan', target: 'Tashkent'},
         {source: 'Vanuatu', target: 'Port-Vila'},
         {source: 'Vatican City (Holy See)', target: 'Vatican City'},
         {source: 'Venezuela', target: 'Caracas'},
         {source: 'Vietnam', target: 'Hanoi'},
         {source: 'Yemen', target: 'Sanaa'},
         {source: 'Zambia', target: 'Lusaka'},
         {source: 'Zimbabwe', target: 'Harare'}
    ]
};