decks.push(
{
    name: 'Capitals of the world',
    description: 'Learn the main capitals of the world with this wonderful deck',
    cards: [
         {source: 'Afghanistan', target: 'Kabul'},
         {source: 'Algeria', target: 'Algiers'},
         {source: 'Angola', target: 'Luanda'},
         {source: 'Argentina', target: 'Buenos Aires'},
         {source: 'Australia', target: 'Canberra'},
         {source: 'Austria', target: 'Vienna'},
         {source: 'Belgium', target: 'Brussels'},
         {source: 'Bolivia', target: 'La Paz'},
         {source: 'Bosnia and Herzegovina', target: 'Sarajevo'},
         {source: 'Brazil', target: 'Brasilia'},
         {source: 'Bulgaria', target: 'Sofia'},
         {source: 'Burkina Faso', target:  'Ouagadougou'},
         {source: 'Cambodia', target: 'Phnom Penh'},
         {source: 'Cameroon', target: 'Yaounde'},
         {source: 'Canada', target: 'Ottawa'},
         {source: 'Cape Verde', target: 'Praia'},
         {source: 'Chile', target: 'Santiago'},
         {source: 'China', target: 'Beijing'},
         {source: 'Colombia', target: 'Bogota'},
         {source: 'Cote d\'Ivoire', target: 'Yamoussoukro'},
         {source: 'Croatia', target: 'Zagreb'},
         {source: 'Cuba', target: 'Havana'},
         {source: 'Czech Republic', target: 'Prague'},
         {source: 'Denmark', target: 'Copenhagen'},
         {source: 'Egypt', target: 'Cairo'},
         {source: 'Ethiopia', target: 'Addis Ababa'},
         {source: 'Finland', target: 'Helsinki'},
         {source: 'France', target: 'Paris'},
         {source: 'Germany', target: 'Berlin'},
         {source: 'Greece', target: 'Athens'},
         {source: 'Haiti', target: 'Port-au-Prince'},
         {source: 'Hungary', target: 'Budapest'},
         {source: 'Iceland', target: 'Reykjavik'},
         {source: 'India', target: 'New Delhi'},
         {source: 'Indonesia', target: 'Jakarta'},
         {source: 'Iran', target: 'Tehran'},
         {source: 'Iraq', target: 'Baghdad'},
         {source: 'Ireland', target: 'Dublin'},
         {source: 'Israel', target: 'Jerusalem'},
         {source: 'Italy', target: 'Rome'},
         {source: 'Jamaica', target: 'Kingston'},
         {source: 'Japan', target: 'Tokyo'},
         {source: 'Kenya', target: 'Nairobi'},
         {source: 'Korea, North', target: 'Pyongyang'},
         {source: 'Korea, South', target: 'Seoul'},
         {source: 'Kuwait', target: 'Kuwait City'},
         {source: 'Lebanon', target: 'Beirut'},
         {source: 'Libya', target: 'Tripoli'},
         {source: 'Lithuania', target: 'Vilnius'},
         {source: 'Luxembourg ', target: 'Luxembourg'},
         {source: 'Madagascar ', target: 'Antananarivo'},
         {source: 'Malaysia', target: 'Kuala Lumpur'},
         {source: 'Mali', target: 'Bamako'},
         {source: 'Mexico', target: 'Mexico City'},
         {source: 'Monaco', target: 'Monaco'},
         {source: 'Mongolia', target: 'Ulaanbaatar'},
         {source: 'Morocco', target: 'Rabat'},
         {source: 'Nepal', target: 'Kathmandu'},
         {source: 'Netherlands ', target: 'Amsterdam'},
         {source: 'New Zealand', target: 'Wellington'},
         {source: 'Norway', target: 'Oslo'},
         {source: 'Pakistan', target: 'Islamabad'},
         {source: 'Paraguay', target: 'Asuncion'},
         {source: 'Peru', target: 'Lima'},
         {source: 'Philippines ', target: 'Manila'},
         {source: 'Poland', target: 'Warsaw'},
         {source: 'Portugal', target: 'Lisbon'},
         {source: 'Romania', target: 'Bucharest'},
         {source: 'Russia', target: 'Moscow'},
         {source: 'Rwanda', target: 'Kigali'},
         {source: 'Saudi Arabia', target: 'Riyadh'},
         {source: 'Senegal', target: 'Dakar'},
         {source: 'Serbia', target: 'Belgrade'},
         {source: 'Sierra Leone', target: 'Freetown'},
         {source: 'Singapore', target: 'Singapore'},
         {source: 'Somalia', target: 'Mogadishu'},
         {source: 'South Africa', target: 'Pretoria'},
         {source: 'Spain', target: 'Madrid'},
         {source: 'Sweden', target: 'Stockholm'},
         {source: 'Switzerland ', target: 'Bern'},
         {source: 'Syria', target: 'Damascus'},
         {source: 'Taiwan', target: 'Taipei'},
         {source: 'Thailand', target: 'Bangkok'},
         {source: 'Togo', target: 'Lome'},
         {source: 'Tunisia', target: 'Tunis'},
         {source: 'Turkey', target: 'Ankara'},
         {source: 'United Arab Emirates', target: 'Abu Dhabi'},
         {source: 'United Kingdom', target: 'London'},
         {source: 'United States of America', target: 'Washington D.C.'},
         {source: 'Uruguay', target: 'Montevideo'},
         {source: 'Venezuela', target: 'Caracas'},
         {source: 'Vietnam', target: 'Hanoi'}
    ]
});