decks.push(
{
    name: 'Hiragana alphabet',
    description: 'Learn the Hiragana alphabet',
    cards: [
         {source: 'あ', target: 'a'},
         {source: 'か', target: 'ka'},
         {source: 'さ', target: 'sa'},
         {source: 'た', target: 'ta'},
         {source: 'な', target: 'na'},
         {source: 'は', target: 'ha'},
         {source: 'ま', target: 'ma'},
         {source: 'や', target: 'ya'},
         {source: 'ら', target: 'ra'},
         {source: 'わ', target: 'wa'},
         {source: 'ん', target: 'n'},

         {source: 'い', target: 'i'},
         {source: 'き', target: 'ki'},
         {source: 'し', target: 'shi'},
         {source: 'ち', target: 'chi'},
         {source: 'に', target: 'ni'},
         {source: 'ひ', target: 'hi'},
         {source: 'み', target: 'mi'},
         {source: 'り', target: 'ri'},

         {source: 'う', target: 'u'},
         {source: 'く', target: 'ku'},
         {source: 'す', target: 'su'},
         {source: 'つ', target: 'tsu'},
         {source: 'ぬ', target: 'nu'},
         {source: 'ふ', target: 'fu'},
         {source: 'む', target: 'mu'},
         {source: 'ゆ', target: 'yu'},
         {source: 'る', target: 'ru'},

         {source: 'え', target: 'e'},
         {source: 'け', target: 'ke'},
         {source: 'せ', target: 'se'},
         {source: 'て', target: 'te'},
         {source: 'ね', target: 'ne'},
         {source: 'へ', target: 'he'},
         {source: 'め', target: 'me'},
         {source: 'れ', target: 're'},

         {source: 'お', target: 'o'},
         {source: 'こ', target: 'ko'},
         {source: 'そ', target: 'so'},
         {source: 'と', target: 'to'},
         {source: 'の', target: 'no'},
         {source: 'ほ', target: 'ho'},
         {source: 'も', target: 'mo'},
         {source: 'よ', target: 'yo'},
         {source: 'も', target: 'mo'},
         {source: 'ろ', target: 'ro'},
         {source: 'を', target: 'wo'}
    ]
});