decks.push(
{
    name: 'Persian alphabet',
    description: 'Learn the Persian alphabet',
    cards: [
         {source: 'آ', target: 'a'},
         {source: 'ب', target: 'b'},
         {source: 'پ', target: 'p'},
         {source: 'ﺕ', target: 't'},
         {source: 'ﺙ', target: 's'},
         {source: 'ﺝ', target: 'j'},
         {source: 'ﭺ', target: 'ch'},
         {source: 'ﺡ', target: 'h'},
         {source: 'ﺥ', target: 'kh'},
         {source: 'ﺩ', target: 'd'},
         {source: 'ﺫ', target: 'z'},
         {source: 'ﺭ', target: 'r'},
         {source: 'ﺯ', target: 'z'},
         {source: 'ژ', target: 'zh'},
         {source: 'ﺱ', target: 's'},
         {source: 'ﺵ', target: 'sh'},
         {source: 'ﺹ', target: 's'},
         {source: 'ﺽ', target: 'z'},
         {source: 'ﻁ', target: 't'},
         {source: 'ﻅ', target: 'z'},
         {source: 'ﻉ', target: 'ayn'},
         {source: 'ﻍ', target: 'gh'},
         {source: 'ﻑ', target: 'f'},
         {source: 'ﻕ', target: 'q'},
         {source: 'ک', target: 'k'},
         {source: 'گ', target: 'g'},
         {source: 'ﻝ', target: 'l'},
         {source: 'ﻡ', target: 'm'},
         {source: 'ﻥ', target: 'n'},
         {source: 'ﻩ', target: 'h'},
         {source: 'و', target: 'v'},
         {source: 'ی', target: 'y'},
    ]
});
